import {escapeHtml as esc} from './components.js';
export function createAdviceWatchUi({api,getLanguage,toast}){
  const dialog=document.querySelector('#adviceWatchDialog');dialog.dataset.localized='true';
  let records=[],view='list',selected=null,pending=false;
  const t=(zh,en)=>getLanguage()==='en-US'?en:zh;
  const errorText=error=>{
    const code=String(error?.message||error).match(/WATCH_[A-Z_]+/)?.[0];
    return ({WATCH_STORE:t('追踪文件无法读取；原文件已保留，请先备份并检查数据。','The watch file could not be read. It has been preserved; back it up and inspect the data.'),WATCH_URL:t('请填写公开的 HTTPS 网页地址，不支持内网、IP 地址或带登录凭据的链接。','Use public HTTPS page URLs, without IP addresses or login credentials.'),WATCH_INPUT:t('请填写标题、建议、1–5 条理由和 1–3 个来源。','Enter a title, advice, 1–5 reasons and 1–3 sources.'),WATCH_BUSY:t('检查正在进行，请完成后再操作。','A check is running. Wait for it to finish.'),WATCH_LIMIT:t('最多可保存 50 条追踪记录。','Up to 50 watches can be saved.'),WATCH_MISSING:t('这条记录已不存在。','This watch no longer exists.')})[code]||t('操作未完成，请检查连接与本地存储后重试。','Could not complete this action. Check your connection and local storage, then retry.');
  };
  const status=r=>r.checking?t('正在检查…','Checking…'):r.paused?t('已暂停','Paused'):({attention:t('发现需确认的影响','Impact needs review'),no_issue_found:t('已检查的来源未发现问题','No issue found in checked sources'),unknown:t('暂未确认','Not yet verified')})[r.lastCheck?.status]||t('尚未检查','Not checked');
  const date=value=>value?new Date(value).toLocaleString(getLanguage()||'zh-CN'):t('无','None');
  const button=(id,label,disabled=false)=>`<button type="button" class="secondary-button" data-watch-action="${id}" ${disabled?'disabled':''}>${label}</button>`;
  const header=title=>`<header><h2>${title}</h2><button type="button" class="text-button" data-watch-close>${t('关闭','Close')}</button></header>`;
  function badge(){const count=records.filter(r=>r.unread).length;document.querySelector('#adviceWatchCount').textContent=count?String(count):'';}
  function update(next){records=next;badge();if(dialog.open&&view!=='edit')render();}
  async function run(fn){if(pending)return;pending=true;try{update(await fn());return true;}catch(error){const el=dialog.querySelector('#watchError');if(el)el.textContent=errorText(error);else toast(errorText(error));return false;}finally{pending=false;}}
  function shell(html){dialog.setAttribute('aria-label',t('建议追踪','Advice tracking'));dialog.innerHTML=html+'<p id="watchError" class="watch-error" role="alert"></p>';dialog.querySelector('[data-watch-close]').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();}
  function findings(check,reasons){
    if(!check)return '';
    reasons=check.reasons||reasons;
    return `<p class="muted">${t('检查时间','Checked')}: ${esc(date(check.checkedAt))}</p>${check.error?`<p class="watch-notice">${check.error==='WATCH_SOURCE_UNAVAILABLE'?t('来源暂不可读取；原有提醒保留。','Sources could not be read; previous alerts are preserved.'):t('模型判断未完成，请连接模型后重试。来源读取不代表建议已核实。','Model review did not finish. Connect a model and retry. Reading a page does not verify the advice.')}</p>`:''}${check.sources?.some(s=>s.truncated)?`<p class="watch-notice">${t('部分来源过长，仅检查了节选，完整内容尚未确认。','Some sources were truncated. Only excerpts were reviewed.')}</p>`:''}${(check.findings||[]).map(f=>`<section class="watch-card"><strong>${esc(reasons[f.reasonIndex]||'')}</strong><p class="watch-status">${({supported:t('来源支持此理由','Source supports this reason'),changed:t('条件变化 · AI 判断，需确认','Conditions changed · AI assessment; verify'),possible_error:t('原建议可能有误 · 待确认','Possible original error · needs verification'),unclear:t('证据不足','Insufficient evidence')})[f.outcome]}</p><p data-user-content>${esc(f.explanation)}</p>${f.previousQuote?`<p>${t('此前来源内容','Earlier source')}</p><blockquote data-user-content>${esc(f.previousQuote)}</blockquote>`:''}${f.quote?`<p>${t('当前来源内容','Current source')}</p><blockquote data-user-content>${esc(f.quote)}</blockquote>`:''}${f.url?`<a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer">${esc(f.url)}</a>`:''}<p data-user-content>${esc(f.nextStep)}</p></section>`).join('')}`;
  }
  function render(){
    if(view==='detail'){
      const r=records.find(r=>r.id===selected);if(!r){view='list';return render();}
      shell(header(esc(r.title))+`<p class="watch-status">${status(r)}</p><p class="muted">${r.automatic?t('应用运行期间每日检查；关闭应用后不检查。','Checks daily while Nodus is running; no checks while closed.'):t('仅手动检查','Manual checks only')}</p><div class="watch-actions">${button('back',t('返回列表','Back'))}${button('check',t('立即检查','Check now'),r.checking||records.some(x=>x.checking))}${button('edit',t('编辑','Edit'),r.checking)}${button(r.paused?'resume':'pause',r.paused?t('恢复追踪','Resume'):t('暂停追踪','Pause'),r.checking)}${button('acknowledge',t('标为已读','Mark read'),r.checking)}${button('alternatives',t('查找替代方案','Find alternatives'),r.checking)}${button('delete',t('删除追踪','Delete watch'),r.checking)}</div><details><summary>${t('采纳的建议与理由','Adopted advice and reasons')}</summary><p data-user-content>${esc(r.advice)}</p><ul>${r.reasons.map(x=>`<li data-user-content>${esc(x)}</li>`).join('')}</ul><p class="muted">${t('采纳时间','Adopted')}: ${esc(date(r.createdAt))}</p></details><div>${r.urls.map(url=>`<p><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(url)}</a></p>`).join('')}</div>${r.lastAlert&&r.lastAlert.checkedAt!==r.lastCheck?.checkedAt?`<details ${r.unread?'open':''}><summary>${t('此前发现的影响（保留供复核）','Earlier impact assessment (retained for review)')}</summary>${findings(r.lastAlert,r.reasons)}</details>`:''}${findings(r.lastCheck,r.reasons)}${r.lastCheck?.sources.some(s=>s.error)?`<p class="watch-notice">${t('以下来源读取失败','Could not read')}: ${r.lastCheck.sources.filter(s=>s.error).map(s=>esc(s.url)).join(', ')}</p>`:''}<details><summary>${t('检查记录','Check history')}</summary>${r.history.map(h=>`<details><summary>${esc(date(h.checkedAt))}</summary>${findings(h,r.reasons)}</details>`).join('')}</details><div id="watchAlternatives"></div>`);
      dialog.querySelectorAll('[data-watch-action]').forEach(el=>el.onclick=async()=>{
        const action=el.dataset.watchAction;
        if(action==='back'){view='list';render();}
        else if(action==='edit')edit(r);
        else if(action==='check')await run(()=>api.checkAdviceWatch(r.id));
        else if(action==='alternatives'){
          el.disabled=true;const output=dialog.querySelector('#watchAlternatives'),errorOutput=dialog.querySelector('#watchError');try{const results=await api.webSearch(`${r.title} alternatives ${r.reasons.join('; ')}`.slice(0,600));output.innerHTML=`<h3>${t('候选来源，尚未核实是否符合你的理由','Candidate sources; suitability not yet verified')}</h3>`+(results.length?results.map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></p>`).join(''):t('未找到结果','No results'));}catch{errorOutput.textContent=t('搜索未完成，请在设置中检查联网搜索连接。','Search failed. Check the web search connection in Settings.');}finally{el.disabled=false;}
        }else if(action==='delete'){
          const area=document.createElement('div');area.className='watch-notice';area.innerHTML=`<p>${t('删除此追踪及检查记录？原对话不受影响。','Delete this watch and its check history? The original chat is preserved.')}</p>${button('confirm-delete',t('确认删除','Confirm delete'))}`;el.after(area);el.disabled=true;area.querySelector('button').onclick=async()=>{if(await run(()=>api.adviceWatchAction(r.id,'delete'))){view='list';render();}};
        }else await run(()=>api.adviceWatchAction(r.id,action));
      });return;
    }
    shell(header(t('建议追踪','Advice tracking'))+`<p class="watch-notice">${t('在回复旁选择“采纳并追踪”，确认采纳理由并添加公开来源。提醒是 AI 对证据的判断，请查看原文后决定。','Choose “Adopt and track” beside a reply, confirm your reasons and add public sources. Alerts are AI assessments; review the evidence before deciding.')}</p><p class="muted">${t('自动检查仅在应用运行期间进行，可能使用模型额度。','Automatic checks run only while the app is open and may consume model credits.')}</p>${records.length?records.map(r=>`<section class="watch-card"><h3 data-user-content>${esc(r.title)} ${r.unread?'●':''}</h3><p>${status(r)}</p><p class="muted">${t('最近检查','Last checked')}: ${esc(date(r.lastCheck?.checkedAt))}</p><button type="button" class="secondary-button" data-watch-id="${esc(r.id)}">${t('查看追踪','View watch')}</button></section>`).join(''):`<p>${t('还没有采纳的建议。','No adopted advice yet.')}</p>`}`);
    dialog.querySelectorAll('[data-watch-id]').forEach(el=>el.onclick=()=>{selected=el.dataset.watchId;view='detail';render();});
  }
  function edit(r){
    view='edit';
    shell(header(t('确认采纳与追踪条件','Confirm adoption and tracking'))+`<form id="watchForm"><label for="watchTitle">${t('标题','Title')}</label><input id="watchTitle" maxlength="120" required value="${esc(r.title||'')}"><label for="watchAdvice">${t('我采纳的建议','Advice I am adopting')}</label><textarea id="watchAdvice" maxlength="12000" required>${esc(r.advice||'')}</textarea><label for="watchReasons">${t('为什么采纳（每行一条，最多 5 条）','Why I am adopting it (one per line, up to 5)')}</label><textarea id="watchReasons" required placeholder="${t('例如：必须离线使用；费用在预算内','For example: must work offline; within my budget')}">${esc((r.reasons||[]).join('\n'))}</textarea><label for="watchSources">${t('公开 HTTPS 来源（每行一个，最多 3 个；优先官方说明）','Public HTTPS sources (one per line, up to 3; prefer official documentation)')}</label><textarea id="watchSources" required>${esc((r.urls||[]).join('\n'))}</textarea><label><input type="checkbox" id="watchAutomatic" ${r.automatic?'checked':''}> ${t('应用运行期间每日自动检查','Check daily while Nodus is running')}</label><p class="watch-notice">${t('保存表示确认采纳。检查时，建议、理由和来源节选会发送给你配置的模型，可能产生费用。仅检查可直接读取的公开网页；需登录或动态加载的页面可能无法核实。编辑建议、理由或来源会重新建立对照。','Saving confirms adoption. Checks send the advice, reasons and source excerpts to your configured model and may incur costs. Only directly readable public pages are supported; login-required or dynamic pages may be unverifiable. Editing advice, reasons or sources starts a new comparison.')}</p><div class="watch-actions"><button type="submit" class="primary-button">${t('确认采纳并保存','Confirm adoption and save')}</button><button type="button" id="watchCancel" class="secondary-button">${t('取消','Cancel')}</button></div></form>`);
    dialog.querySelector('#watchCancel').onclick=()=>{view=r.id?'detail':'list';selected=r.id;render();};
    dialog.querySelector('#watchForm').onsubmit=async event=>{
      event.preventDefault();if(pending)return;
      const value=id=>dialog.querySelector(id).value.trim();
      const input={id:r.id,taskId:r.taskId,title:value('#watchTitle'),advice:value('#watchAdvice'),reasons:value('#watchReasons').split('\n').filter(Boolean),urls:value('#watchSources').split('\n').filter(Boolean),automatic:dialog.querySelector('#watchAutomatic').checked,language:getLanguage()};
      const submit=dialog.querySelector('[type=submit]');submit.disabled=true;
      if(await run(()=>api.saveAdviceWatch(input))){view='detail';selected=r.id||records[0].id;render();}else submit.disabled=false;
    };
  }
  return {
    async initialize(){if(!api.listAdviceWatches)return;try{update(await api.listAdviceWatches());}catch(error){toast(errorText(error));}api.onAdviceWatches(next=>{const previous=new Set(records.filter(r=>r.unread).map(r=>r.id));const fresh=next.some(r=>r.unread&&!previous.has(r.id));update(next);if(fresh)toast(t('已采纳的建议有新的变化，请查看建议追踪。','An adopted recommendation needs review. Open Advice tracking.'));});document.querySelector('#adviceWatchButton').onclick=()=>{view='list';render();};},
    adopt(task,event){if(!event)return;edit({title:event.text.slice(0,80).replace(/\s+/g,' '),advice:event.text,reasons:[],urls:(event.sources||[]).map(s=>s.url).filter(url=>url.startsWith('https://')).slice(0,3),automatic:false,taskId:task.id});},
  };
}
