import {escapeHtml as esc} from './components.js';

export function createMemoryUi({api,t,persist,toast}){
  const dialog=document.createElement('dialog');dialog.id='reviewedMemory';dialog.className='safety-dialog memory-dialog';dialog.dataset.localized='';document.body.append(dialog);
  let data,taskId,busy=false,editing=null;
  const status=value=>({candidate:t('候选 · 尚未使用','Candidate · not in use'),approved:t('已审阅','Reviewed'),active:t('生效 · 参考上下文','Active · reference context'),revoked:t('已撤销','Revoked'),'source-changed':t('暂停 · 来源已修改','Paused · source changed'),'source-unavailable':t('暂停 · 来源任务已删除','Paused · source task deleted'),'source-project-changed':t('暂停 · 来源已移出项目','Paused · source moved out of project'),'restricted-source':t('暂停 · 来源权限受限','Paused · source restricted'),'other-scope':t('不适用于当前任务','Outside current scope')})[value]||value;
  const scopeOptions=(value,project=data.project)=>`<option value="task" ${value==='task'?'selected':''}>${t('仅来源任务','Source task only')}</option>${project?`<option value="project" ${value==='project'?'selected':''}>${t('所属项目：','Project: ')}${esc(project.name)}</option>`:''}`;
  const selectedSource=()=>data.sources.find(s=>s.id===dialog.querySelector('#memorySource').value);
  async function perform(fn,allowStop=false){if(busy)return;busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=!(allowStop&&b.id==='stopMemorySuggestion'));try{await fn();data=await api.memoryDescribe(taskId);render();}catch(error){dialog.querySelector('#memoryError').textContent=String(error.message||error);}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);updateSource();}}
  function updateSource(){dialog.querySelector('#stopMemorySuggestion').disabled=!busy;const source=selectedSource(),area=dialog.querySelector('#memorySourceText');area.textContent=source?.preview||t('由你直接填写。保存后仍先进入候选列表。','Written by you. Saving still creates a candidate.');dialog.querySelector('#memoryQuote').disabled=!source;dialog.querySelector('#suggestMemories').disabled=busy||!source||data.restricted;}
  function render(){
    dialog.setAttribute('aria-label',t('可审阅、可撤销的记忆','Reviewable, revocable memory'));
    dialog.innerHTML=`<div class="safety-heading"><div><small>${esc(data.title||'Nodus')}</small><h2>${t('可审阅、可撤销的记忆','Reviewable, revocable memory')}</h2></div><button id="closeMemory" class="secondary-button">${t('关闭','Close')}</button></div>
      <p>${t('记忆只作为参考，不加入任务要求，也不改变权限。外部材料提炼出的经验先进入候选，逐条审阅后才会用于指定范围。','Memories are references, not task requirements or permissions. Observations from external material remain candidates until you review each one and its scope.')}</p>
      <p class="safety-note">${t('撤销会停止正在使用记忆的调用，并阻止后续直接注入。已经发送的内容和已生成的答复、作品不会被撤回；需要去除这些历史影响时，请使用隔离重试。','Revocation stops calls using memory and prevents future direct injection. Already sent content and existing answers or outputs cannot be recalled; use isolated retry to remove that historical context.')}</p>
      <details id="memoryNew" open><summary>${t('添加候选记忆','Add a candidate memory')}</summary><label>${t('来自哪里','Source')}<select id="memorySource"><option value="note">${t('我直接填写','Write my own note')}</option>${data.sources.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}${s.kind==='conversation'?t('（对话背景）',' (conversation background)'):''}</option>`).join('')}</select></label>
      <pre class="safety-payload" id="memorySourceText"></pre><label>${t('来源原文摘录（逐字引用）','Exact source quotation')}<textarea id="memoryQuote" rows="2" maxlength="4000"></textarea></label><label>${t('希望记住什么','What to remember')}<textarea id="memoryContent" rows="3" maxlength="2000"></textarea></label><label>${t('适用范围','Scope')}<select id="memoryScope">${scopeOptions('task')}</select></label>
      <div class="safety-actions"><button id="createMemory" class="primary-button">${t('保存为候选','Save as candidate')}</button><button id="suggestMemories" class="secondary-button">${t('用当前模型提炼候选','Suggest candidates with current model')}</button></div><p class="safety-note">${t('模型提炼会发送所选来源的前 12,000 字，可能产生费用；最多生成 3 条，绝不会自动启用。私密或禁止外发的来源不用于自动提炼。','Model suggestions send up to 12,000 characters from the selected source and may incur fees. At most 3 candidates are created; none activate automatically. Restricted sources are excluded.')}</p></details>
      <button id="stopMemorySuggestion" class="secondary-button">${t('停止当前提炼','Stop current extraction')}</button><p id="memoryError" role="alert"></p><h3>${t('记住了什么、来源与适用范围','Contents, provenance and scope')}</h3><div id="memoryRecords">${data.records.map(recordMarkup).join('')||`<p>${t('还没有记忆。','No memories yet.')}</p>`}</div>`;
    dialog.querySelector('#closeMemory').onclick=()=>dialog.close();dialog.querySelector('#stopMemorySuggestion').onclick=()=>api.stopTask({taskId}).catch(e=>toast(e.message));dialog.querySelector('#memorySource').onchange=updateSource;
    dialog.querySelector('#createMemory').onclick=()=>perform(()=>api.memoryCreate({taskId,sourceId:dialog.querySelector('#memorySource').value,quote:dialog.querySelector('#memoryQuote').value,content:dialog.querySelector('#memoryContent').value,scope:dialog.querySelector('#memoryScope').value}));
    dialog.querySelector('#suggestMemories').onclick=()=>perform(()=>api.memorySuggest({taskId,sourceId:dialog.querySelector('#memorySource').value,scope:dialog.querySelector('#memoryScope').value}),true);
    dialog.querySelectorAll('[data-memory-action]').forEach(button=>button.onclick=()=>{const r=data.records.find(r=>r.id===button.dataset.id),action=button.dataset.memoryAction;if(action==='edit'){editing=r.id;render();return;}if(action==='cancel'){editing=null;render();return;}void perform(async()=>{let payload={taskId,id:r.id,revision:r.revision,action};if(action==='approve'){if(!dialog.querySelector(`[data-confirm-memory="${r.id}"]`)?.checked)throw Error(t('请先核对内容、原文与适用范围，并勾选确认。','Review the content, quote and scope, then check the confirmation.'));payload.confirmation='approve-memory';}if(action==='save'){payload={...payload,action:'edit',content:dialog.querySelector('#editMemoryText').value,scope:dialog.querySelector('#editMemoryScope').value};}await api.memoryAction(payload);editing=null;});});updateSource();
  }
  function recordMarkup(r){const edit=editing===r.id,available=['candidate','revoked','active'].includes(r.availability),button=(action,label)=>`<button class="secondary-button" data-memory-action="${action}" data-id="${r.id}">${label}</button>`;
    return `<article class="memory-record" data-memory-id="${r.id}"><strong>${status(r.availability)}</strong><p class="memory-text">${esc(r.text)}</p><dl><dt>${t('适用于','Applies to')}</dt><dd>${r.scope.kind==='project'?t('项目','Project'):t('任务','Task')} · ${esc(r.scopeName)}</dd><dt>${t('来源','Source')}</dt><dd>${esc(r.source.taskTitle)} → ${esc(r.source.name)}${r.source.origin?`<small>${esc(r.source.origin)}</small>`:''}</dd><dt>${t('记录方式','Recorded by')}</dt><dd>${r.method==='model'?`${t('模型提炼','Model extraction')} · ${esc(r.model?.id||'')}`:t('用户添加','User added')}</dd></dl><details><summary>${t('查看原文与修改历史','View original quote and edit history')}</summary><blockquote>${esc(r.source.quote)}</blockquote><ol class="memory-history">${r.history.map(h=>`<li><strong>${({candidate:t('创建候选','Candidate created'),approve:t('用户审阅并启用','Reviewed and enabled'),revoke:t('用户撤销','Revoked by user'),edit:t('修改后重新待审','Edited; awaiting review'),'previous-text':t('修改前的内容','Previous content')})[h.action]||esc(h.action)}</strong><small>${esc(new Date(h.at).toLocaleString())}</small>${h.text?`<p>${esc(h.text)}</p>`:''}${h.scope?`<small>${t('当时范围：','Previous scope: ')}${esc(h.scope.name||h.scope.id)}</small>`:''}</li>`).join('')}</ol></details>
      ${edit?`<label>${t('修改内容（重新进入候选）','Edit content (returns to candidate)')}<textarea id="editMemoryText" rows="3" maxlength="2000">${esc(r.text)}</textarea></label><label>${t('适用范围','Scope')}<select id="editMemoryScope">${scopeOptions(r.scope.kind,r.sourceProject)}</select></label><div class="safety-actions">${button('save',t('保存并重新审阅','Save for review'))}${button('cancel',t('取消','Cancel'))}</div>`:`${r.status!=='approved'&&available?`<label class="safety-check"><input type="checkbox" data-confirm-memory="${r.id}">${t('我已核对内容、原文和范围；仅将其作为参考','I reviewed the content, quotation and scope for use as reference')}</label>`:''}<div class="safety-actions">${r.status!=='approved'&&available?button('approve',t('审阅后启用','Approve for use')):''}${r.status==='approved'?button('revoke',t('撤销','Revoke')):''}${button('edit',t('编辑并重新审阅','Edit for review'))}${button('delete',t('删除此记忆','Delete memory'))}</div>`}</article>`;
  }
  return {async open(id){try{await persist();taskId=id;editing=null;data=await api.memoryDescribe(id);render();if(!dialog.open)dialog.showModal();}catch(error){toast(error.message);}}};
}
