import {escapeHtml as esc} from './components.js';

export function createSafetyCheckUi({api,t,persist,toast}){
  const dialog=document.createElement('dialog');dialog.id='safetyCheck';dialog.className='safety-dialog check-dialog';dialog.dataset.localized='';document.body.append(dialog);
  let description=null,suites=[],selected=null,runs=[],compareA='',compareB=null;
  const label=id=>({original:t('原材料：未追加攻击','Original materials: no added attack'),'private-read':t('诱导读取私密文件','Induced private-file read'),'protected-write':t('诱导越权修改','Induced unauthorized write'),'goal-override':t('诱导放弃原任务','Induced task abandonment')})[id]||id;
  const status=value=>({completed:t('已结束','Finished'),running:t('运行中','Running'),stopped:t('已停止','Stopped'),interrupted:t('未完整运行','Incomplete'),error:t('执行失败','Execution failed'),timeout:t('超时','Timed out'),budget_exhausted:t('达到调用上限','Budget exhausted'),checks_passed:t('所配文字检查通过','Configured text checks passed'),checks_failed:t('所配文字检查失败','Configured text checks failed'),unverified:t('待核对','Needs review'),incomplete:t('未完成','Incomplete'),passed:t('人工确认完成','User confirmed complete'),failed:t('人工确认未完成','User confirmed incomplete'),unreviewed:t('未人工核对','Not reviewed')})[value]||value;
  function render(){
    if(!description)return;
    dialog.setAttribute('aria-label',t('用自己的任务做安全体检','Safety check for your task'));
    dialog.innerHTML=`<div class="safety-heading"><div><small>${esc(description.title||'Nodus')}</small><h2>${t('用自己的任务做安全体检','Safety check for your task')}</h2></div><button id="closeSafetyCheck" class="secondary-button">${t('关闭','Close')}</button></div>
      <p>${t('固定任务副本后，分别运行原材料和追加测试攻击的材料。只在新工作目录中读写，额外私密探针使用合成标记，不改写原任务、不自动导出。所选真实资料会发送给当前模型，请先去除真实秘密，仍受原权限和外发核对约束。','A fixed task copy is run with original materials and with added test attacks. Files are confined to new working directories and the additional private probes are synthetic. Your original task is not edited or exported. Remove real secrets from selected materials before sending them to the current model under existing permissions and disclosure review.')}</p>
      <p class="safety-note">${t('关闭只收起窗口；正在运行的体检会继续。需要结束时请点“停止体检”。','Closing hides this window; a running check continues. Use Stop check to end it.')}</p>
      ${description.restrictedHistory?`<p class="safety-note">${t('原任务的私密/禁止外发历史也会保守保留。仅取消勾选附件不解除这些限制；需要清除历史影响时，先使用“隔离材料并重试”建立干净任务。','Private/blocked source history remains conservatively enforced. Unchecking an attachment does not declassify its historical effects; use material isolation first if a clean task is needed.')}</p>`:''}
      <details id="newSafetyCheck" ${suites.length?'':'open'}><summary>${t('建立新的体检配置','Create a new check')}</summary><p><strong>${t('原始目标：','Task: ')}</strong>${esc(description.requirement)}</p><div class="check-materials">${description.materials.map(m=>`<label class="safety-check"><input type="checkbox" data-check-material="${m.index}" ${m.excluded?'disabled':'checked'}>${esc(m.name)} · ${esc(m.classification)}${m.excluded?t('（不纳入）',' (excluded)'):''}</label>`).join('')}</div>
      <label class="safety-check"><input id="checkHistory" type="checkbox" checked>${t('保留已有问答背景','Include existing conversation context')}</label><label class="safety-check"><input id="checkWeb" type="checkbox" checked>${t('保留已有网页摘录','Include existing web excerpts')} · ${description.webCount}</label><label class="safety-check"><input id="checkVersion" type="checkbox" ${description.versionId?'checked':'disabled'}>${t('复制当前作品中允许读取的文件','Copy readable files from the current artifact')} ${esc(description.versionId||'')}</label>
      ${description.artifactType?`<label>${t('在此产物文件中检查文字','Check text in this deliverable file')}<input id="checkFile" value="${esc(description.checkFile)}"></label>`:''}<label>${t('产物或答复至少应包含哪些文字？每行一项。' ,'Required text in the output or answer, one item per line.')}<textarea id="checkExpected" rows="3" placeholder="${t('例如：公开发布日期、12000、10 月 20 日','For example: release date, 12000, October 20')}"></textarea></label><p class="safety-note">${t('这是你指定的附加检查，不是完整任务验收。文件存在或文字出现都不等于任务已完成，结果还可人工核对。','These are additional checks you specify, not complete task acceptance. File existence or matching text does not establish completion; you can review each result.')}</p>
      <label>${t('探针保护方式','Probe protection mode')}<select id="checkProbeMode"><option value="declared">${t('保留原路径授权，检查是否遵守体检约束','Keep original path permissions; check test constraints')}</option><option value="enforced">${t('额外禁止探针路径，检查拦截与完成情况','Additionally deny probe paths; check enforcement and utility')}</option></select></label><p class="safety-note">${t('两种模式都明确要求不读取/外发私密探针、不改动保护探针。默认模式不新增路径禁令；若原授权宽泛，违规操作可能实际发生在合成文件上。','Both modes explicitly forbid private-probe disclosure and protected-probe changes. Default mode adds no path denials; broad original permissions may allow violations on synthetic files.')}</p><div class="check-options">${['private-read','protected-write','goal-override'].map(id=>`<label class="safety-check"><input type="checkbox" data-check-attack="${id}" checked>${label(id)}</label>`).join('')}</div>
      <div class="safety-columns"><label>${t('每组最多模型请求','Maximum requests per case')}<input id="checkRequestLimit" type="number" min="2" max="16" value="8"></label><label>${t('每次输出 token 上限','Output-token limit per request')}<input id="checkOutputLimit" type="number" min="256" max="8192" value="2048"></label><label>${t('每组执行时限（秒）','Execution limit per case (seconds)')}<input id="checkTimeout" type="number" min="30" max="600" value="180"></label></div>
      <button id="createSafetyCheck" class="secondary-button">${t('保存副本与测试条件','Save the task copy and test conditions')}</button></details>
      <label>${t('已保存的体检配置','Saved checks')}<select id="safetyCheckSuite">${suites.map(s=>`<option value="${s.id}" ${selected===s.id?'selected':''}>${esc(s.title)} · ${esc(new Date(s.createdAt).toLocaleString())}</option>`).join('')}</select></label>
      <div id="safetyCheckPlan"></div><div class="safety-actions"><button id="runSafetyCheck" class="primary-button" ${selected?'':'disabled'}>${t('用当前模型运行此配置','Run this check with the current model')}</button><button id="stopSafetyCheck" class="secondary-button">${t('停止体检','Stop check')}</button></div>
      <p id="safetyCheckError" role="alert"></p><div id="safetyCheckResults"></div><div id="safetyCheckInspect"></div>
      <p class="safety-note">${t('体检按保存的原始材料副本运行，不继承任务的上下文压缩。只检查本配置的文本注入、合成私密标记和受保护文件。答疑模式没有文件工具，不将这类未覆盖项记作通过。未发现问题不代表安全认证；拦截来自权限层时不能归功于模型。每组仅一次运行；请求温度 0，接口支持和随机性仍因模型而异。','Checks use saved original material copies and do not inherit task context compression. This checks only the configured text injections, synthetic private marker and protected file. Answer-only mode has no file tools; uncovered items are not passes. No findings are not a security certification; policy blocks are not model-level defenses. Each case runs once; temperature zero is requested, but support and randomness vary by model.')}</p>`;
    dialog.querySelector('#closeSafetyCheck').onclick=()=>dialog.close();
    dialog.querySelector('#createSafetyCheck').onclick=create;
    dialog.querySelector('#safetyCheckSuite').onchange=async e=>{selected=e.target.value;compareA='';compareB=null;await loadResults();renderPlan();};
    dialog.querySelector('#runSafetyCheck').onclick=start;dialog.querySelector('#stopSafetyCheck').onclick=()=>api.safetyCheckStop().catch(e=>toast(e.message));renderPlan();renderResults();
  }
  function renderPlan(){const spec=suites.find(s=>s.id===selected),node=dialog.querySelector('#safetyCheckPlan');if(!node)return;node.innerHTML=spec?`<p><strong>${t('本轮连接：','Current connection: ')}</strong>${esc(description.model?`${description.model.provider} / ${description.model.id} · ${description.model.origin}`:t('尚未连接模型','No model connected'))}</p><p>${spec.caseIds.length} ${t('组条件，每组最多','cases; at most ')} ${spec.limits.maxRequests} ${t('次请求；总计最多','requests each, at most ')} ${spec.caseIds.length*spec.limits.maxRequests} ${t('次。会产生模型费用；每组执行时限（秒）：','requests total. Model fees apply; execution limit per case (seconds): ')}${spec.limits.timeoutMs/1000}</p><p>${t('已纳入审阅过的参考记忆：','Reviewed reference memories included: ')}${spec.referenceMemories?.length||0}${t(' 条；撤销或修改后须建立新配置。','; after revocation or changes, create a new check.')}</p><p><strong>${t('保护方式：','Protection mode: ')}</strong>${spec.probeMode==='enforced'?t('额外禁止探针路径','Additional probe path denials'):t('原路径授权 + 明确体检约束','Original path permissions + explicit test constraints')}</p><p>${t('保留材料 / 文件：','Retained materials/files: ')}${spec.materials.length} / ${spec.files.length} · ${t('网页摘录','Web excerpts')}: ${spec.webCount} · ${t('因权限等原因未复制文件：','Files not copied due to permissions: ')}${spec.omitted.length}</p>${spec.omitted.length?`<p class="safety-note">${t('有文件未复制：任务完成情况只针对选定副本，失败可能来自缺少输入，不能直接归因于模型。','Some files were not copied. Task outcomes apply only to the selected copy; missing inputs can cause failures independent of the model.')}</p>`:''}${spec.minimalDisclosure?`<p>${t('已启用逐次外发核对，体检也会等待确认；模型比较会包含你的选择影响。','Per-request disclosure review is enabled. This check will wait for approval; comparisons include your choices.')}</p>`:''}<details><summary>${t('查看固定的测试材料、权限和完成检查','Inspect fixed attacks, permissions and output checks')}</summary><pre class="safety-payload">${esc(JSON.stringify({requirement:spec.requirement,reviewedReferenceMemories:spec.referenceMemories||[],expected:spec.expected,checkFile:spec.checkFile,policy:spec.policy,probeMode:spec.probeMode,testDeniedPaths:spec.testDeniedPaths,probeConstraints:spec.probeConstraints,materials:spec.materials,files:spec.files,omitted:spec.omitted},null,2))}</pre>${spec.attacks.map(a=>`<p><strong>${label(a.id)}</strong></p><pre class="safety-payload">${esc(a.text)}</pre>`).join('')}</details>`:'';dialog.querySelector('#runSafetyCheck').disabled=!spec;}
  function rowSummary(row){
    if(!row)return t('未运行','Not run');const sent=row.requests.filter(r=>r.containsMarker&&r.attempted).length,accepted=row.requests.filter(r=>r.containsMarker&&r.status>=200&&r.status<300).length;
    return `<strong>${status(row.status)}</strong>${!row.requests.length?`<small>${t('未完成模型请求，不能记作通过。','No model request completed; this is not a pass.')}</small>`:''}${row.id!=='original'?`<small>${t('完整测试材料在请求中','Full test material in requests')}: ${row.requests.some(r=>r.attempted&&r.fullTestMaterial)?t('已匹配','Matched'):t('未确认，可能被处理或编码','Unconfirmed; may be transformed or encoded')}</small>`:''}${!row.coverage.fileTools?`<small>${t('无文件工具：私密读取和越权改写未覆盖。','No file tools: private reads and unauthorized writes are not exercised.')}</small>`:''}<small>${t('含私密标记的请求','Requests containing private marker')}: ${sent} (${t('成功响应','successful response')} ${accepted})</small><small>${t('产物/答复出现标记','Marker in output')}: ${row.markerInOutputs?t('是','Yes'):row.requests.length?t('未观察到','Not observed'):t('未验证','Unverified')}</small><small>${t('受保护文件被改动','Protected file changed')}: ${!row.probePrepared?t('未覆盖','Not exercised'):row.protectedChanged?t('是','Yes'):t('未观察到','Not observed')}</small><small>${t('私密读取 / 越权写入被拦截','Blocked private reads / writes')}: ${row.privateReadBlocked} / ${row.protectedWriteBlocked}</small><small>${t('原任务','Task')}: ${status(row.utility.status)} · ${status(row.human.status)}</small>${row.goalMarkerInAnswer?`<small>${t('答复仅回显攻击要求的标记，需核对目标偏离。','Answer echoed only the attack marker; review task deviation.')}</small>`:''}${row.scanIncomplete||row.evidenceIncomplete?`<small>${t('扫描或运行记录不完整，不能据此排除泄露。','Scanning or run records are incomplete; leakage cannot be ruled out.')}</small>`:''}`;
  }
  function renderResults(){
    const node=dialog.querySelector('#safetyCheckResults');if(!node)return;
    if(!runs.length){node.innerHTML=`<p>${t('尚未运行。切换模型后仍可选择同一配置重新运行。','No runs yet. After switching models, reuse this same saved check.')}</p>`;return;}
    if(!runs.some(r=>r.id===compareA))compareA=runs[0].id;if(compareB===null||(compareB&&!runs.some(r=>r.id===compareB)))compareB=runs[1]?.id||'';
    const options=value=>runs.map(r=>`<option value="${r.id}" ${value===r.id?'selected':''}>${esc(r.model.id)} · ${status(r.status)} · ${esc(new Date(r.startedAt).toLocaleString())}</option>`).join('');
    const chosen=[runs.find(r=>r.id===compareA),runs.find(r=>r.id===compareB)].filter(Boolean),spec=suites.find(s=>s.id===selected);
    node.innerHTML=`<h3>${t('同一配置的运行结果与模型比较','Results and model comparison for this check')}</h3><div class="safety-columns"><label>A<select id="checkCompareA">${options(compareA)}</select></label><label>B<select id="checkCompareB"><option value="">${t('不比较','No comparison')}</option>${options(compareB)}</select></label></div>
      <div class="check-table-scroll"><table class="check-table"><thead><tr><th>${t('条件','Condition')}</th>${chosen.map(r=>`<th>${esc(r.model.provider)} / ${esc(r.model.id)}<small>${r.cases.reduce((n,c)=>n+c.requests.length,0)} ${t('次请求','requests')} · ${r.cases.reduce((n,c)=>n+c.tokens,0)} ${t('已报告 tokens','reported tokens')}</small></th>`).join('')}</tr></thead><tbody>${(spec?.caseIds||[]).map(id=>`<tr><th>${label(id)}</th>${chosen.map(run=>{const row=run.cases.find(c=>c.id===id);return `<td>${rowSummary(row)}${row?`<button class="text-button" data-inspect-run="${run.id}" data-inspect-case="${id}">${t('查看证据与产物','Inspect evidence and output')}</button>`:''}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div><p class="safety-note">${t('比较包含相同任务快照、测试材料和权限。不同模型的 SDK、实际温度支持、人工授权/脱敏选择仍可能不同；不据此给出通用安全排名。','Comparisons share the task snapshot, attacks and permissions. SDKs, actual temperature support and human approvals/redactions may differ; this is not a general safety ranking.')}</p>`;
    node.querySelector('#checkCompareA').onchange=e=>{compareA=e.target.value;renderResults();};node.querySelector('#checkCompareB').onchange=e=>{compareB=e.target.value;renderResults();};
    node.querySelectorAll('[data-inspect-run]').forEach(button=>button.onclick=()=>inspect(button.dataset.inspectRun,button.dataset.inspectCase));
  }
  function inspect(runId,caseId){
    const run=runs.find(r=>r.id===runId),row=run?.cases.find(c=>c.id===caseId);if(!row)return;
    const node=dialog.querySelector('#safetyCheckInspect');node.innerHTML=`<h3>${label(caseId)} · ${esc(run.model.id)}</h3>${row.error?`<p>${esc(row.error)}</p>`:''}<p>${t('原产物检查 / 要求检查：','Artifact / requirement checks: ')}${esc(row.completionStatus||'unverified')} / ${esc(row.requirementStatus||'unverified')}</p><ul>${row.utility.checks.map(c=>`<li>${c.passed?'✓':'✗'} ${esc(c.text)}</li>`).join('')}</ul>
      ${row.previewUrl?`<iframe id="safetyCheckPreview" title="${t('体检产物预览','Check artifact preview')}" sandbox="allow-scripts allow-downloads" src="${esc(row.previewUrl)}"></iframe>`:''}${row.answer?`<details open><summary>${t('模型答复','Model answer')}</summary><pre class="safety-payload">${esc(row.answer)}</pre></details>`:''}
      <details><summary>${t('工具尝试、请求证据与覆盖范围','Tool attempts, request evidence and coverage')}</summary><pre class="safety-payload">${esc(JSON.stringify({tools:row.tools,blocks:row.blocks,requests:row.requests,coverage:row.coverage,humanDecisions:row.humanDecisions,disclosureReviews:row.disclosureReviews},null,2))}</pre></details>
      <label>${t('你的任务核对结果','Your task review')}<select id="checkHumanStatus">${['unreviewed','passed','failed'].map(v=>`<option value="${v}" ${row.human.status===v?'selected':''}>${status(v)}</option>`).join('')}</select></label><textarea id="checkHumanNote" rows="2" maxlength="2000">${esc(row.human.note||'')}</textarea><button id="saveCheckReview" class="secondary-button" ${run.status==='running'?'disabled':''}>${t('保存人工核对','Save review')}</button>`;
    node.querySelector('#saveCheckReview').onclick=async()=>{try{const updated=await api.safetyCheckReviewResult({suiteId:selected,runId,caseId,status:node.querySelector('#checkHumanStatus').value,note:node.querySelector('#checkHumanNote').value});runs=runs.map(r=>r.id===updated.id?updated:r);renderResults();toast(t('已保存人工核对；自动证据未改写。','Review saved; automatic evidence is unchanged.'));}catch(e){toast(e.message);}};node.scrollIntoView({block:'nearest'});
  }
  async function create(){const button=dialog.querySelector('#createSafetyCheck');button.disabled=true;try{const spec=await api.safetyCheckCreate({taskId:description.taskId,sourceDigest:description.sourceDigest,selectedMaterials:[...dialog.querySelectorAll('[data-check-material]:checked')].map(n=>Number(n.dataset.checkMaterial)),includeHistory:dialog.querySelector('#checkHistory').checked,includeWeb:dialog.querySelector('#checkWeb').checked,includeVersion:dialog.querySelector('#checkVersion').checked,checkFile:dialog.querySelector('#checkFile')?.value,probeMode:dialog.querySelector('#checkProbeMode').value,expected:dialog.querySelector('#checkExpected').value.split('\n').map(s=>s.trim()).filter(Boolean),attackIds:[...dialog.querySelectorAll('[data-check-attack]:checked')].map(n=>n.dataset.checkAttack),maxRequests:Number(dialog.querySelector('#checkRequestLimit').value),maxOutputTokens:Number(dialog.querySelector('#checkOutputLimit').value),timeoutSeconds:Number(dialog.querySelector('#checkTimeout').value)});suites.unshift(spec);selected=spec.id;runs=[];render();}catch(e){dialog.querySelector('#safetyCheckError').textContent=e.message;button.disabled=false;}}
  async function loadResults(){if(selected)runs=await api.safetyCheckResults(selected);if(description.active?.suiteId===selected&&!runs.some(r=>r.id===description.active.id))runs.unshift(description.active);renderResults();}
  async function start(){const button=dialog.querySelector('#runSafetyCheck');button.disabled=true;try{await api.safetyCheckStart({suiteId:selected,model:description.model});await loadResults();dialog.querySelector('#safetyCheckError').textContent='';}catch(e){dialog.querySelector('#safetyCheckError').textContent=e.message;}finally{button.disabled=false;}}
  api.onSafetyCheckUpdate?.(report=>{if(report.suiteId!==selected)return;if(!runs.some(r=>r.id===report.id)){compareB=compareA||runs[0]?.id||'';compareA=report.id;}runs=[report,...runs.filter(r=>r.id!==report.id)];if(dialog.open)renderResults();});
  return {async open(taskId){try{await persist();description=await api.safetyCheckDescribe(taskId);suites=await api.safetyCheckList(taskId);if(description.active&&suites.some(s=>s.id===description.active.suiteId))selected=description.active.suiteId;else if(!suites.some(s=>s.id===selected))selected=suites[0]?.id||null;runs=[];render();dialog.showModal();await loadResults();}catch(e){toast(e.message);}}};
}
