import {escapeHtml as esc} from './components.js';

export function createTaskBudgetUi({api,getTask,getLanguage,persist,toast}){
  const t=(zh,en)=>getLanguage()==='en-US'?en:zh,n=value=>Number(value||0).toLocaleString(),money=value=>'$'+Number(value||0).toFixed(6);
  const dialog=document.createElement('dialog');dialog.id='taskBudget';dialog.className='safety-dialog budget-dialog';dialog.dataset.localized='';document.body.append(dialog);
  let data,taskId,busy=false,previewSequence=0;
  const phase=value=>({planning:t('规划','Planning'),execution:t('执行','Execution'),checking:t('检查','Checking')})[value]||value;
  const status=value=>({disabled:t('未开启','Disabled'),'needs-plan':t('待拆解','Needs decomposition'),review:t('待确认分配','Review allocation'),ready:t('已启用','Ready'),reported:t('已报告','Reported'),unknown:t('用量未知，保留额度','Unknown usage; allowance retained'),reserved:t('已预留','Reserved'),sent:t('请求已发出','Sent'),cancelled:t('未发送，已释放','Not sent; released')})[value]||value;
  async function refresh(){const task=getTask();if(!task||!api.budgetGet)return;try{const next=await api.budgetGet(task.id);if(getTask()?.id!==task.id)return;const button=document.querySelector('#budgetButton');if(button){button.textContent=next.enabled?t(`预算 · ${n(next.remaining)}`,`Budget · ${n(next.remaining)}`):t('任务预算','Task budget');button.title=t('剩余生成 token；点击查看分阶段预算和费用','Remaining generation tokens; view stage budgets and costs');}if(dialog.open&&taskId===task.id&&!busy){data=next;render();}}catch(error){if(dialog.open)toast(error.message);}}
  async function action(fn){if(busy)return;busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=b.id!=='stopBudgetWork');try{await fn();data=await api.budgetGet(taskId);render();await refresh();}catch(error){dialog.querySelector('#budgetError').textContent=String(error.message||error);}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);dialog.querySelector('#approveBudget')?.toggleAttribute('disabled',data.status!=='review');dialog.querySelector('#decomposeBudget')?.toggleAttribute('disabled',!data.enabled);}}
  function totals(){
    const rows=['planning','execution','checking'].map(stage=>{const calls=data.calls.filter(c=>c.stage===stage),spent=calls.reduce((s,c)=>s+(c.charge||0),0),prior=calls.filter(c=>c.planId!==data.planId).reduce((s,c)=>s+(c.charge||0),0),allocated=prior+data.nodes.filter(s=>s.stage===stage).reduce((s,c)=>s+c.allocated,0),known=calls.reduce((s,c)=>s+(c.cost??0),0),unknown=calls.filter(c=>c.cost==null&&c.status!=='cancelled').length;return `<tr><th>${phase(stage)}</th><td>${data.nodes.length?n(allocated):'—'}</td><td>${n(spent)}</td><td>${data.nodes.length?n(Math.max(0,allocated-spent)):'—'}</td><td>${money(known)}${unknown?`<small>${unknown} ${t('次费用未知','calls with unknown cost')}</small>`:''}</td></tr>`;}).join('');
    return `<div class="budget-summary"><strong>${t('总额度','Total allowance')}: ${n(data.total)}</strong><strong>${t('已用或占用','Used or reserved')}: ${n(data.used)}</strong><strong>${t('剩余','Remaining')}: ${n(data.remaining)}</strong></div><p>${t('已知费用估算','Known estimated cost')}: <b>${money(data.knownCost)}</b>${data.unknownCostCalls?` · ${data.unknownCostCalls} ${t('次调用费用未知，不代表免费','calls have unknown cost, not zero cost')}`:''}</p><p>${t('接口已报告：输入 / 生成 / 其中推理','Provider reported: input / generated / reasoning within generated')}: ${n(data.reportedInput)} / ${n(data.reportedOutput)} / ${data.reportedReasoning?n(data.reportedReasoning):t('未单列','not separately reported')}${data.unknownUsageCalls?` · ${data.unknownUsageCalls} ${t('次用量待核对，已保守占用上限','calls have unknown usage, retaining their caps')}`:''}</p><div class="budget-table-wrap"><table><thead><tr><th>${t('阶段','Stage')}</th><th>${t('额度','Allowance')}</th><th>${t('已用/占用','Used/reserved')}</th><th>${t('剩余','Remaining')}</th><th>${t('费用估算','Estimated cost')}</th></tr></thead><tbody>${rows}</tbody></table></div>`;
  }
  function render(){dialog.setAttribute('aria-label',t('任务预算模式','Task budget mode'));dialog.innerHTML=`<div class="safety-heading"><div><small>${esc(data.title||'Nodus')}</small><h2>${t('任务预算模式','Task budget mode')}</h2></div><button id="closeBudget" class="secondary-button">${t('关闭','Close')}</button></div>
    <p>${t('先拆解，再按复杂度给规划、执行子任务和检查分配额度。拆解本身也计入规划花费；执行不能借走检查额度。安全体检和新建的隔离任务使用独立额度。','Decompose first, then allocate tokens by complexity to planning, execution steps and checking. Decomposition is charged to planning; execution cannot borrow checking allowance. Safety assessments and new clean-retry tasks use separate allowances.')}</p>
    <p class="safety-note">${t('预算单位为生成 token，包含服务商计入生成用量的推理 token。当前不单独控制内部思考；实际请求必须带生成上限，否则停止。输入 token 单独统计，费用按你填写的价格估算，不是服务商账单或费用硬上限。','The budget counts generation tokens, including reasoning counted by the provider as output. Internal thinking is not capped separately. Requests must carry an output limit or stop. Input is tracked separately; cost uses your rates, not a provider invoice or a hard dollar cap.')}</p>
    <p><strong>${status(data.status||'disabled')}</strong>${data.stale?` · ${t('任务已变化，请重新拆解；历史用量不会清零','Task changed; decompose again. Past usage is retained.')}`:''}</p><section id="budgetLive">${totals()}</section>
    <details id="budgetSettings" ${data.enabled?'':'open'}><summary>${t('设置预算与价格','Budget and pricing settings')}</summary><label class="safety-check"><input id="budgetEnabled" type="checkbox" ${data.enabled?'checked':''}>${t('开启任务预算','Enable task budget')}</label><div class="safety-columns"><label>${t('整项任务生成 token 总额度','Total generation tokens')}<input id="budgetTotal" type="number" min="4000" max="1000000" value="${data.total}"></label><label>${t('每次请求上限','Per-request cap')}<input id="budgetRequestCap" type="number" min="256" max="32768" value="${data.perRequest}"></label><label>${t('累计请求次数上限','Cumulative request limit')}<input id="budgetCalls" type="number" min="3" max="1000" value="${data.maxCalls}"></label></div>
    <label class="safety-check"><input id="budgetPriceEnabled" type="checkbox" ${data.prices?'checked':''}>${t('填写当前模型价格（美元 / 百万 token）','Set current-model prices (USD per million tokens)')}</label><div class="safety-columns">${[['input','输入','Input'],['output','生成（含推理）','Output incl. reasoning'],['cacheRead','缓存读取','Cache read'],['cacheWrite','缓存写入','Cache write']].map(([key,zh,en])=>`<label>${t(zh,en)}<input id="budgetPrice-${key}" type="number" min="0" step="any" value="${data.prices?.[key]??''}"></label>`).join('')}</div><p class="safety-note">${t('价格只用于后续调用，适用于配置时的模型与接收方；换模型后重新填写。没有价格时显示未知。调整总额度不会抹掉已用量；保存后须重新拆解并确认分配。','Prices apply to future calls on the configured model and recipient; update them after switching. Missing prices stay unknown. Changing the total retains usage and requires a new reviewed allocation.')}</p><button id="saveBudget" class="secondary-button">${t('保存设置','Save settings')}</button></details>
    <div class="safety-actions"><button id="decomposeBudget" class="primary-button" ${data.enabled?'':'disabled'}>${t('用当前模型拆解并分配','Decompose and allocate with current model')}</button><button id="stopBudgetWork" class="secondary-button">${t('停止当前任务调用','Stop current task call')}</button></div>
    <p class="safety-note">${t('拆解会调用当前模型，最多申请 2,048 个生成 token，并遵守已有外发授权。复杂度是估计；可核对和调整。这里的步骤不能新增用户要求或扩大工具权限。','Decomposition calls the current model with at most 2,048 output tokens and existing disclosure permissions. Complexity is an estimate you can review and adjust. Steps cannot add user requirements or tool permissions.')}</p>
    <div id="budgetPlan">${data.nodes.map(s=>`<article class="memory-record"><strong>${phase(s.stage)}${s.stage==='execution'?` · ${esc(s.title)}`:''}</strong><p>${esc(s.goal)}</p><p>${t('分配依据：','Allocation rationale: ')}${esc(s.reason)}</p><label>${t('复杂度（1–5）','Complexity (1–5)')}<input data-budget-weight="${s.id}" type="number" min="1" max="5" value="${s.complexity}" ${data.status==='review'?'':'disabled'}></label><p>${t('本轮分配','This allocation')}: ${n(s.allocated)} token · ${t('已用/占用','Used/reserved')}: ${n(s.spent)} · ${t('剩余','Remaining')}: ${n(Math.max(0,s.allocated-(s.spent||0)))}</p></article>`).join('')}</div><button id="approveBudget" class="primary-button" ${data.status==='review'?'':'disabled'}>${t('确认拆解与预算分配','Confirm decomposition and allocation')}</button><p id="budgetError" role="alert"></p>
    <details><summary>${t('调用明细与历史','Calls and history')}</summary><div id="budgetReceipts">${data.calls.slice().reverse().map(c=>`<p><strong>${phase(c.stage)} · ${esc(c.nodeTitle||c.nodeId)} · ${status(c.status)}</strong><br>${esc(c.model?.id||'')} · ${esc(c.at)}<br>${t('申请上限 / 记账','Requested cap / charged')}: ${n(c.cap)} / ${n(c.charge)} · ${c.cost==null?t('费用未知','Cost unknown'):money(c.cost)}</p>`).join('')||t('尚无调用','No calls yet')}</div></details>`;
    dialog.querySelector('#closeBudget').onclick=()=>dialog.close();dialog.querySelector('#stopBudgetWork').onclick=()=>api.stopTask({taskId}).catch(e=>toast(e.message));
    dialog.querySelector('#saveBudget').onclick=()=>action(()=>api.budgetConfigure({taskId,revision:data.revision,enabled:dialog.querySelector('#budgetEnabled').checked,total:Number(dialog.querySelector('#budgetTotal').value),perRequest:Number(dialog.querySelector('#budgetRequestCap').value),maxCalls:Number(dialog.querySelector('#budgetCalls').value),prices:dialog.querySelector('#budgetPriceEnabled').checked?Object.fromEntries(['input','output','cacheRead','cacheWrite'].map(k=>[k,dialog.querySelector('#budgetPrice-'+k).value===''?null:Number(dialog.querySelector('#budgetPrice-'+k).value)])):null}));
    dialog.querySelector('#decomposeBudget').onclick=()=>action(async()=>{await persist();await api.budgetPlan({taskId});});
    dialog.querySelectorAll('[data-budget-weight]').forEach(input=>input.onchange=async()=>{const sequence=++previewSequence;try{const nodes=await api.budgetPreview({taskId,revision:data.revision,weights:[...dialog.querySelectorAll('[data-budget-weight]')].map(el=>Number(el.value))});if(sequence===previewSequence){data.nodes=nodes;render();}}catch(error){dialog.querySelector('#budgetError').textContent=error.message;}});
    dialog.querySelector('#approveBudget').onclick=()=>action(()=>api.budgetApprove({taskId,revision:data.revision,weights:[...dialog.querySelectorAll('[data-budget-weight]')].map(el=>Number(el.value))}));
  }
  api.onBudgetUpdate?.(next=>{if(dialog.open&&next.taskId===taskId){data={...data,...next};const live=dialog.querySelector('#budgetLive');if(live)live.innerHTML=totals();}void refresh();});
  const button=document.querySelector('#budgetButton');if(button){button.dataset.localized='';button.onclick=()=>void open();}
  async function open(){const task=getTask();if(!task)return;try{await persist();taskId=task.id;data=await api.budgetGet(taskId);render();dialog.showModal();}catch(e){toast(e.message);}}
  return {open,refresh};
}
