import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {StorageService} from '../backend/storage.mjs';
import {PiService} from '../backend/pi-service.mjs';
import {ArtifactService} from '../backend/artifact-service.mjs';
import {finalizeArtifact} from '../backend/artifacts.mjs';
import {SafetyService,defaultPolicy} from '../backend/safety-service.mjs';

test('full production artifact flow recovers a denied read, omits restricted audit content, and retains review evidence on restore',async()=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'nodus-artifact-recovery-'));
  const storage=new StorageService(root);await storage.initialize();
  const safety=new SafetyService({file:path.join(root,'safety.json')});await safety.initialize();storage.safety=safety;
  const task={id:'t',artifactType:'website',requirement:'Change only the public heading to Safe outcome.'};
  await safety.setPolicy(task.id,{...defaultPolicy(),deniedPaths:['restricted'],destinations:['model|https://api.deepseek.com']},0);
  const base=await storage.prepareVersion('t','v0'),canary='SYNTHETIC_AUDIT_PRIVATE_b6af1d';await mkdir(path.join(base,'restricted'));
  await writeFile(path.join(base,'index.html'),'<html><body><h1>Old heading</h1></body></html>');await writeFile(path.join(base,'restricted/secret.txt'),canary);await finalizeArtifact(task,base);
  const pi=new PiService({piDir:storage.piDir,safety,emit:()=>{}});await pi.initialize();await pi.modelRuntime.setRuntimeApiKey('deepseek','synthetic-key');pi.model=pi.modelRuntime.getModel('deepseek','deepseek-flash');pi.providerId='deepseek';pi.modelId=pi.model.id;
  let phase,step=0;const contexts=[],runText=pi.runText.bind(pi);
  pi.runText=args=>{phase=args.phase;return runText(args);};
  pi.modelRuntime.prepareRequest=async(model,options)=>({model,options,provider:{streamSimple(_model,context){
    contexts.push(JSON.stringify(context));
    const actions=[{name:'read',arguments:{path:'restricted/secret.txt'}},{name:'write',arguments:{path:'index.html',content:'<html><body><h1>Safe outcome</h1></body></html>'}}];
    const action=phase==='requirement-audit'?null:actions[step++];
    const message={role:'assistant',api:model.api,provider:'deepseek',model:model.id,timestamp:0,usage:{input:0,output:0,cacheRead:0,cacheWrite:0,totalTokens:0,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:action?'toolUse':'stop',content:action?[{type:'toolCall',id:'step-'+step,...action}]:[{type:'text',text:phase==='requirement-audit'?'{"results":[]}':'Done'}]};
    return {async *[Symbol.asyncIterator](){yield {type:'done',reason:message.stopReason,message};},result:async()=>message};
  }}});
  const artifacts=new ArtifactService(storage,pi);
  const result=await artifacts.execute({task,versionId:'v1',versionLabel:'v1',baseVersionId:'v0'});
  assert.equal(result.artifact.safetyReview.deniedReads,1);assert.equal(result.completion.status,'needs_review');
  assert(result.completion.results.some(r=>r.kind==='safety-recovery'));
  assert.deepEqual(result.requirementAudit.scope.omittedFiles,['restricted/secret.txt']);
  assert(!contexts.some(c=>c.includes(canary)),'audit must not reintroduce the file that the tool boundary withheld');
  assert.match(await readFile(path.join(storage.versionDir('t','v1'),'index.html'),'utf8'),/Safe outcome/);
  assert.equal(await readFile(path.join(base,'restricted/secret.txt'),'utf8'),canary);
  const restored=await artifacts.restore({taskId:'t',sourceVersionId:'v1',versionId:'v2'});
  assert.equal(restored.completion.status,'needs_review');assert(restored.completion.results.some(r=>r.kind==='safety-recovery'));
  const saved=JSON.parse(await readFile(path.join(storage.versionDir('t','v2'),'artifact.json'),'utf8'));assert.equal(saved.safetyReview.deniedReads,1);
});
