const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("forma", {
  platform: process.platform,
  compressionGet:id=>ipcRenderer.invoke('forma:compression-get',id),
  compressionCreate:input=>ipcRenderer.invoke('forma:compression-create',input),
  compressionGenerate:input=>ipcRenderer.invoke('forma:compression-generate',input),
  compressionAction:input=>ipcRenderer.invoke('forma:compression-action',input),
  budgetGet:id=>ipcRenderer.invoke('forma:budget-get',id),
  budgetConfigure:input=>ipcRenderer.invoke('forma:budget-configure',input),
  budgetPlan:input=>ipcRenderer.invoke('forma:budget-plan',input),
  budgetApprove:input=>ipcRenderer.invoke('forma:budget-approve',input),
  budgetPreview:input=>ipcRenderer.invoke('forma:budget-preview',input),
  onBudgetUpdate:listener=>{const handler=(_event,value)=>listener(value);ipcRenderer.on('forma:budget-update',handler);return ()=>ipcRenderer.removeListener('forma:budget-update',handler);},
  memoryDescribe:id=>ipcRenderer.invoke('forma:memory-describe',id),
  memoryCreate:input=>ipcRenderer.invoke('forma:memory-create',input),
  memoryAction:input=>ipcRenderer.invoke('forma:memory-action',input),
  memorySuggest:input=>ipcRenderer.invoke('forma:memory-suggest',input),
  safetyDraft:payload=>ipcRenderer.invoke('forma:safety-draft',payload),
  safetyPending:()=>ipcRenderer.invoke('forma:safety-pending'),
  safetyGet:taskId=>ipcRenderer.invoke('forma:safety-get',taskId),
  safetyPolicy:payload=>ipcRenderer.invoke('forma:safety-policy',payload),
  safetySource:payload=>ipcRenderer.invoke('forma:safety-source',payload),
  safetyResolve:(requestId,choice)=>ipcRenderer.invoke('forma:safety-resolve',{requestId,choice}),
  disclosureSetting:input=>ipcRenderer.invoke('forma:disclosure-setting',input),
  disclosurePending:()=>ipcRenderer.invoke('forma:disclosure-pending'),
  disclosurePreview:input=>ipcRenderer.invoke('forma:disclosure-preview',input),
  disclosureSend:(id,token)=>ipcRenderer.invoke('forma:disclosure-send',{id,token}),
  disclosureDeny:id=>ipcRenderer.invoke('forma:disclosure-deny',id),
  onDisclosureRequests:listener=>{const handler=(_event,value)=>listener(value);ipcRenderer.on('forma:disclosure-requests',handler);return ()=>ipcRenderer.removeListener('forma:disclosure-requests',handler);},
  safetyRecoveryReview:input=>ipcRenderer.invoke('forma:safety-recovery-review',input),
  safetyRecoveryPreview:input=>ipcRenderer.invoke('forma:safety-recovery-preview',input),
  safetyRecoveryAnalyze:input=>ipcRenderer.invoke('forma:safety-recovery-analyze',input),
  safetyRecoveryCommit:id=>ipcRenderer.invoke('forma:safety-recovery-commit',id),
  safetyRecoveryRun:id=>ipcRenderer.invoke('forma:safety-recovery-run',id),
  safetyRecoveryOriginals:id=>ipcRenderer.invoke('forma:safety-recovery-originals',id),
  safetyCheckDescribe:id=>ipcRenderer.invoke('forma:safety-check-describe',id),
  safetyCheckCreate:input=>ipcRenderer.invoke('forma:safety-check-create',input),
  safetyCheckList:id=>ipcRenderer.invoke('forma:safety-check-list',id),
  safetyCheckResults:id=>ipcRenderer.invoke('forma:safety-check-results',id),
  safetyCheckStart:id=>ipcRenderer.invoke('forma:safety-check-start',id),
  safetyCheckStop:()=>ipcRenderer.invoke('forma:safety-check-stop'),
  safetyCheckReviewResult:input=>ipcRenderer.invoke('forma:safety-check-review-result',input),
  onSafetyCheckUpdate:listener=>{const handler=(_event,value)=>listener(value);ipcRenderer.on('forma:safety-check-update',handler);return ()=>ipcRenderer.removeListener('forma:safety-check-update',handler);},
  onSafetyRequests:listener=>{const handler=(_event,value)=>listener(value);ipcRenderer.on('forma:safety-requests',handler);return ()=>ipcRenderer.removeListener('forma:safety-requests',handler);},
  onSafetyRecord:listener=>{const handler=(_event,value)=>listener(value);ipcRenderer.on('forma:safety-record',handler);return ()=>ipcRenderer.removeListener('forma:safety-record',handler);},
  openSource:url=>ipcRenderer.invoke('forma:open-source',url),
  onMenuCommand: listener => {
    const handler=(_event,command)=>listener(command);
    ipcRenderer.on('forma:menu-command',handler);
    return ()=>ipcRenderer.removeListener('forma:menu-command',handler);
  },
  getAppearance: () => ipcRenderer.invoke("forma:appearance"),
  setTheme: theme => ipcRenderer.invoke("forma:set-theme", theme),
  setLanguage: language => ipcRenderer.invoke('forma:set-language',language),
  onAppearance: listener => {
    const handler = (_event, appearance) => listener(appearance);
    ipcRenderer.on("forma:appearance", handler);
    return () => ipcRenderer.removeListener("forma:appearance", handler);
  },
  listAdviceWatches:()=>ipcRenderer.invoke('forma:advice-list'),
  saveAdviceWatch:input=>ipcRenderer.invoke('forma:advice-save',input),
  adviceWatchAction:(id,action)=>ipcRenderer.invoke('forma:advice-action',{id,action}),
  checkAdviceWatch:id=>ipcRenderer.invoke('forma:advice-check',id),
  onAdviceWatches:listener=>{const handler=(_event,records)=>listener(records);ipcRenderer.on('forma:advice-watches',handler);return ()=>ipcRenderer.removeListener('forma:advice-watches',handler);},
  bootstrap: () => ipcRenderer.invoke("forma:bootstrap"),
  searchStatus: () => ipcRenderer.invoke('forma:search-status'),
  configureSearch: config => ipcRenderer.invoke('forma:configure-search',config),
  restoreSearch: () => ipcRenderer.invoke('forma:restore-search'),
  webSearch: (query,taskId) => ipcRenderer.invoke('forma:web-search',{query,taskId}),
  checkUpdate: () => ipcRenderer.invoke('forma:check-update'),
  downloadUpdate: () => ipcRenderer.invoke('forma:download-update'),
  installUpdate: config => ipcRenderer.invoke('forma:install-update',config),
  openUpdateInstaller: () => ipcRenderer.invoke('forma:open-update-installer'),
  openUpdatePage: () => ipcRenderer.invoke('forma:open-update-page'),
  onUpdateProgress: listener => {
    const handler=(_event,progress)=>listener(progress);
    ipcRenderer.on('forma:update-progress',handler);
    return ()=>ipcRenderer.removeListener('forma:update-progress',handler);
  },
  uninstallNodus: () => ipcRenderer.invoke('forma:uninstall-nodus'),
  openUninstallHelp: () => ipcRenderer.invoke('forma:open-uninstall-help'),
  saveState: state => ipcRenderer.invoke("forma:save-state", state),
  exportBackup: () => ipcRenderer.invoke('forma:export-backup'),
  readClipboard: () => ipcRenderer.invoke('forma:read-clipboard'),
  chooseDeliveryDirectory: taskId=>ipcRenderer.invoke('forma:choose-delivery-directory',taskId),
  exportVersion: payload=>ipcRenderer.invoke('forma:export-version',payload),
  openVersionDirectory: payload=>ipcRenderer.invoke('forma:open-version-directory',payload),
  configureModel: config => ipcRenderer.invoke("forma:configure-model", config),
  restoreCredential: () => ipcRenderer.invoke('forma:restore-credential'),
  activateConnection: id => ipcRenderer.invoke('forma:activate-connection',id),
  removeConnection: id => ipcRenderer.invoke('forma:remove-connection',id),
  stopTask: payload => ipcRenderer.invoke("forma:stop-task", payload),
  disconnectModel: () => ipcRenderer.invoke("forma:disconnect-model"),
  openPlugins: () => ipcRenderer.invoke("forma:open-plugins"),
  selectMaterials: () => ipcRenderer.invoke("forma:select-materials"),
  importMaterial: payload => ipcRenderer.invoke("forma:import-material", payload),
  generateOptions: payload => ipcRenderer.invoke("forma:generate-options", payload),
  taskWorkspace: taskId => ipcRenderer.invoke('forma:task-workspace',taskId),
  nextDecision: payload => ipcRenderer.invoke('forma:next-decision',payload),
  oneShotChat: payload => ipcRenderer.invoke("forma:one-shot-chat", payload),
  classifyMessage: payload => ipcRenderer.invoke('forma:classify-message',payload),
  executeArtifact: payload => ipcRenderer.invoke("forma:execute-artifact", payload),
  executeGoat: payload => ipcRenderer.invoke('forma:execute-goat',payload),
  executeWebsite: payload => ipcRenderer.invoke("forma:execute-website", payload),
  proposeRevision: payload => ipcRenderer.invoke("forma:propose-revision", payload),
  executeRevision: payload => ipcRenderer.invoke("forma:execute-revision", payload),
  restoreVersion: payload => ipcRenderer.invoke("forma:restore-version", payload),
  onExecutionEvent: listener => {
    const handler = (_event, payload) => listener(payload);
    ipcRenderer.on("forma:execution-event", handler);
    return () => ipcRenderer.removeListener("forma:execution-event", handler);
  },
});
